### ISSUE TITLE
Feature: User can remove villagers from favorites list

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/my-villagers#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove villagers from their favorites list. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When users are on the 'Favorites' list screen, they will have the option to click on a 'heart' to remove a villager.  A modal will prompt them to make sure they want to remove the villager before proceeding. When users are browsing through villagers on the home view, they will also have an option to remove a villager in the "villager information modal" by clicking on the 'heart' icon in the villager information.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-10-07 at 12 19 02 PM](https://user-images.githubusercontent.com/109825222/194638157-22e590a5-7d22-4f16-82b0-1cbdaeb0a7f9.png)
![Screen Shot 2022-10-07 at 12 19 11 PM](https://user-images.githubusercontent.com/109825222/194638170-017a2e9f-9908-4ab4-aec5-7635978ed10e.png)

![Screen Shot 2022-10-07 at 12 19 27 PM](https://user-images.githubusercontent.com/109825222/194638185-b8f61eb9-574a-490e-bd77-369b2b608620.png)
![Screen Shot 2022-10-07 at 12 22 23 PM](https://user-images.githubusercontent.com/109825222/194638532-c6d1d9b6-946c-470a-bea5-8ab554a95146.png)
![Screen Shot 2022-10-07 at 12 22 32 PM](https://user-images.githubusercontent.com/109825222/194638541-566a14fc-0f67-4db5-83d6-e7b638b7815c.png)

![Screen Shot 2022-10-07 at 12 20 01 PM](https://user-images.githubusercontent.com/109825222/194638221-02cd3d50-cfef-40bb-96fd-77779240c12b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create a div to add a 'heart' icon to the favorite villager card.
- [ ] Style the 'heart icon'
- [ ] Add a `div` and create a modal container for the 'Are you sure you want to remove.....' message. 
- [ ] Add two buttons to the modal container. Give one an `id` of 'go-back' and another with an `id` of 'delete'
- [ ] Create an `addEventListener` on the favorites card to listen for `click` on the heart and will:
     - [ ] Open the 'are you sure....' modal
- [ ] Create an `addEventListener` on the modal and listen for `click` on the two buttons
   - [ ] If user clicks on button with id `go-back` then close out of the modal
   - [ ] If user clicks on the button with id `delete` then update data model. 
     - [ ] Delete the favorite villager from the favoritesList in the data model
     - [ ] Remove the favorite villager from the Favorites List DOM tree
- [ ] Check that the villager is removed from lists
- [ ] Add to the `$modalContainer` a similar event when user clicks on the 'heart' icon when the heart is filled. 
- [ ] Add text: 'Villager Removed' and style it similarly to the 'Added to Favorites' text
- [ ] Include a `setTimeOut` to have text appear and then disappear. 
- [ ] Check to make sure the different modals are registering removal of villagers.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
