### ISSUE TITLE
Feature: User can search for villagers

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/my-villagers#23]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can search for villagers

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When users go to the home page, there will be a search bar where they will have the option to search for specific villagers.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2023-03-03 at 3 02 57 PM](https://user-images.githubusercontent.com/109825222/222851443-d036a440-25d4-40fd-9ec7-b0ee8e3db1c0.png)
![Screen Shot 2023-03-03 at 3 03 14 PM](https://user-images.githubusercontent.com/109825222/222851483-f3746846-e68a-43f9-ba8b-449cfddd3695.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create a search container `div` on the home page. 
- [ ] Create a form element that will contain a text input and button 
- [ ] Style the text input and button to match the Figma
- [ ] Query select for the search form
- [ ] Add event listener for the submission of search results
- [ ] Change the styling of the species list to 'hide' the species
- [ ] Generate DOMTree elements to create a new DOM Tree with just the search result element
- [ ] Create an option to clear the search result / reset the DOM tree 
- [ ] Unhide the rest of the villagers
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
