### ISSUE TITLE
Feature: User can view their favorites list 

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/my-villagers#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of their favorite villagers. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user selects their favorite villagers, they will have option to select the "heart" icon on the navigation bar to view a their favorite villagers. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-26 at 10 41 20 AM](https://user-images.githubusercontent.com/109825222/192344373-b4ee46b6-85d5-4d4d-b839-1c66ce036cb4.png)
![Screen Shot 2022-09-26 at 10 41 40 AM](https://user-images.githubusercontent.com/109825222/192344423-3dcc959a-cf22-4588-aef3-9baab595858a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add to the nav bar an anchor tag for 'favorites' and 'heart' icon for the favorites page 
- [x] Style using CSS
- [x] Create an event listener for when the user clicks on the 'favorites' or 'heart' icon
- [x] Change the 'home' icon's class name to make icon unfilled
- [x] Add a sibling `div[data-view = "favorites-view"]`
- [x] Add a heading for 'Favorites' 
- [x] Add default 'no villagers liked' text 
- [x] Create a new pop-up container with id:` 'home-info'`
- [x] Add 'x', image icon, and text to pop-up container 
- [x] Style using CSS
- [x] Add an event listener for the 'x' button and make the 'home-info' container hidden
- [x] Add new versions of the previously created pop-up containers to favorites page
- [x] Change their CSS columns to 'column-half' for the desktop view
- [x] Add new event listeners to the duplicated pop-up containers & make their content disappear 
- [x] Add an empty unordered list to the `div[data-view = "favorites-view"]`
- [x] Add some sample villagers to the unordered list in HTML and style them to match the wireframe 
- [x] Check that villagers look good on both mobile and desktop screens
- [x] Define a function that takes a single 'favorite' object and returns a DOM tree that matches one of the examples in the HTML 
- [x] Create a loop to create a DOM tree for each favorite villager in the data model and append it to the page when the `DOMContentLoaded` event is fired
- [x] Remove the example villager entries once user's favorites are successfully being appended to the DOM on page load
- [x] Create a condition that will hide the 'pop-ups' and default text once  there are favorite entries.
- [x] Ensure that adding a new villager to the 'favorites' list will add it to the page 
- [x] Ensure that clicking on 'favorites' or the 'heart' icon will take users to the favorites page with correct villagers loaded
- [x] Ensure that refreshing the pages shows the same view as before refreshing
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
